name: apexive
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #external packages
  flutter_svg: ^2.0.10+1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  hydrated_bloc: ^9.1.5

  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  path_provider: ^2.1.2
  get_it: ^7.6.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.6




# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Thin.ttf
